defaults: &defaults
  adapter: postgresql
  username: scardinho
  password: 

development:
  <<: *defaults
  database: new_relic_log_test_development

production:
  <<: *defaults
  database: new_relic_log_test_production
